### PR TITLE
Create a new pull request from unsuccessful PR selection views

### PR DESCRIPTION
**Pull request by BinaryMuse**
When a PR can't be found for a branch, or many PRs are found for a branch, offer a link to the create PR page for the branch on GitHub.com.

Also adds a new button to re-do the search, useful if the user creates the PR in another window and wants to display it in Atom.

cursor_and_github__preview__ ___atom

### CODE REVIEW

**Comment by smashwilson** [comment]
Random, drive-by bikeshedding:

* I feel like "open a new pull request" should be the first, more visually dominant option. It seems like it'd be the most common, happy-path next step here; create a branch, create a PR.
* Maybe change the text "Submit" to "Pin"? "Submit" sounds a bit like "submit PR", especially right next to the actual create PR action.

(As always, feel free to disregard entirely :smile:)

**Comment by simurai** [comment]
> @smashwilson (As always, feel free to disregard entirely 😄)

I regard entirely 😄 . Here how a flip around version could be:

image

**Comment by 50Wliu** [comment]
I think in the case where a branch hasn't been pushed yet, only one button is needed that could read "Push and open new pull request".  Because you can already push through the status bar.

**Comment by BinaryMuse** [comment]
@smashwilson @simurai Totally agree, good call. Love the mockup, I'll work on that.

I punted on pushing from this UI at first because the GitHub tab components don't have the active repository passed down through it like the Git tab does, but this is something I can remedy. :)

**Comment by BinaryMuse** [comment]
@simurai We've gotten feedback before (#830) that "pinning" is somewhat confusing. I think the language is probably problematic. What do you think about changing this language to something like "linking a pull request with this branch," or "associating" or something else similar?

**Comment by simurai** [comment]
> @50Wliu only one button is needed that could read "Push and open new pull request".

Yeah, that would be even better.

> @BinaryMuse I punted on pushing from this UI at first because the GitHub tab components don't have the active repository passed down through it like the Git tab does, but this is something I can remedy. :)

Ah, you mean that the GitHub tab doesn't know anything about the status (pushed or not) of the current repo? Also, I guess opening the browser with the github.com compare page would need to be delayed until the push is done, right? So that it can show the changes.

**Comment by simurai** [comment]
> @BinaryMuse We've gotten feedback before (#830) that "pinning" is somewhat confusing. I think the language is probably problematic. What do you think about changing this language to something like "linking a pull request with this branch," or "associating" or something else similar?

Hmm.. yeah. Maybe "you can manually link a GitHub pull request..". 👍  "Associate" is kinda mouthful.

**Comment by krainboltgreene** [comment]
Would love to have this, any chance I can help?

**Comment by kuychaco** [comment]
@krainboltgreene thanks for the comment and offer to help! We're currently working on a refactor to better enable this feature in #1230. So hopefully we'll pick this back up soon :)

**Comment by am** [comment]
Any progress on this? Looks like the refactor is merged. Is there any plans to continue this feature?

**Comment by smashwilson** [comment]
Closing in favor of #1376 since the codebase has moved on quite a bit since this was opened.

**Pull request closed without merging**
