### PR TITLE
More links to .com

### PR DESCRIPTION
**Pull request by simurai**
### Description of the Change

This adds a bunch of links to github.com on the PR detail page.

- [x] PR title (no hover effect)
- [x] A link in the footer
- [x] Commit sha
- [x] Timestamp of comments

screen shot 2018-07-19 at 5 27 48 pm

### Alternate Designs

An alternative would be to open everything inside Atom, but currently that's not possible/feassable.

### Benefits

Users have a way to continue on .com to get more infos or do certain actions.

### Possible Drawbacks

None

### Applicable Issues

Part of https://github.com/atom/github/issues/1582

### CODE REVIEW

**Comment by simurai** [comment]
I'm stuck adding more links. For example, I tried to turn the sha into a link to the commit with `href={commit.commitUrl}`. I also added `commitUrl` in graphql query, but it doesn't output anything.

I saw a bunch of `lib/views/__generated__/....Query.graphql.js`. Do these need to be generated somehow? Anyways, I'll add the `help-needed` label, if someone wants to continue. 🙇

**Comment by smashwilson** [comment]
> Do these need to be generated somehow?

Ahhhh, yup. If you edit `graphql` literals, you need to run `npm run relay` to recompile all of the GraphQL fragments. It's... weird.

**Comment by smashwilson** [comment]
(We've just been checking the generated GraphQL files in to version control, as well.)

**Comment by simurai** [comment]
> you need to run `npm run relay` to recompile all of the GraphQL fragments.

That worked! 🙌  Ok, I think this is ready.

We _could_ also link avatars and usernames and more stuff, but that's a bit more complex when there are [multiple names](https://github.com/atom/github/blob/abb2be24971fd180b2cf4abd7607f1b02f5b5669/lib/views/timeline-items/commits-view.js#L68-L78) involved. I also ran into failing specs, hence the force-pushes ☝️.

**Pull request merged**
