### PR TITLE
⬆️ Bump superstring from 2.4.2 to 2.4.3

### PR DESCRIPTION
**Pull request by DeeDeeG**
**Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

### Description of the Change

Update the indirect dependency `superstring` to 2.4.3 in `package-lock.json`. This was mostly a compatibility update for building against newer Node/Electron versions. (See: https://github.com/atom/superstring/pull/80). Allows this package to be built against at least Electron 7.

(This PR is needed for the _"Transpiling packages with custom transpiler configurations"_ step of Atom's `script/build` with Electron 7.)

More context:

I noticed @sadick254 has been updating several packages that would allow Atom to be built against Electron 7 (or even newer??). Thank you @sadick254!!!

This update in the `github` package is apparently the last compatibility update that would be needed before Atom can build against Electron 7. I have personally built Atom against Electron 7 with all the updated packages + this change. _(More work would be needed to make Atom actually work as intended on Electron 7, but hey, at least it builds now!)_

### Screenshot or Gif

N/A

### Applicable Issues

https://github.com/atom/superstring/pull/80

### CODE REVIEW

**Comment by smashwilson** [comment]
Thanks!

**Comment by DeeDeeG** [comment]
CI passed 🎉 ~~_(except somehow Codecov is pretty sure this decreases JS test coverage, which I'm pretty sure it doesn't!)_~~ Oh actually Codecov is cool with this now.

**Comment by smashwilson** [comment]
Yeah, Codecov unifies coverage results from each platform build as they complete, so it almost always reports a coverage decrease, then an increase.

Also if Codecov wasn't happy with a `package-lock.json` change it would just be noise and I'd ignore it anyway 😂

**Comment by DeeDeeG** [comment]
Last comment I have for this thread... (beyond scope of/unrelated to this PR but there's no obvious place to mention it): Apparently this allows Atom to build on macOS, but it's not quite there yet on Windows and Linux still. 

CI run on my fork of Atom: https://dev.azure.com/DeeDeeG/b/_build/results?buildId=882&view=results

(no response expected, just wanted to document this somewhere)

**Pull request merged**
