### PR TITLE
Visual tweaks to Github's Remote Selector & No Remote views

### PR DESCRIPTION
**Pull request by robertrossmann**
**Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* Suggestion: You can use checklists to keep track of progress for the sections on metrics, tests, documentation, and user research.

### Description of the Change

This PR attempts to visually improve some of the less used views in the Github pane, namely:

- NoRemotes view - shown when Github pane cannot detect any git remotes for the current workspace
- RemoteSelector view - shown when there are multiple remotes configured for the current workspace

The overall idea behind all of these improvements was to make it as much consistent as possible with the Git tab's "Initialise git repository" view from the Git tab. Overall, the following changes have been made:

- UI elements' text selection has been disabled and the cursor is now forced to the classic pointer
- Content is now moved vertically to the centre of the pane
- Buttons are now stretched to the full pane's width
- All margins and paddings match those used in the Git tab's "initialise git repository" view
- ⚠️ A git icon has been added to these views
  > I would rather see a nice octocat icon there since the views are related to Github but I posses neither skills nor tools to craft such a vector graphic 🤷‍♂️

#### Baseline

> The goal of this PR is to make the other views look more like this one.

baseline

#### Before

multiple remotes - before changes

buttons disappearing

no repo - before changes

#### After

multiple remotes - after changes

buttons are resized

no repo - after changes

### Alternate Designs

N/A

### Benefits

Visually more pleasant experience when these views appear. 🎨

### Possible Drawbacks

🤷‍♂️ 

### Applicable Issues

Could not find any.

### Metrics

N/A

### Documentation

N/A

### Release Notes

N/A

### User Experience Research (Optional)

N/A

### CODE REVIEW

**Comment by vanessayuenn** [comment]
Thanks for opening this PR @robertrossmann! 🎉 I think it's a great improvement on the remotes view. CC-ing @simurai for design 👀, maybe he will have input on which icon to use also:

>⚠️ A git icon has been added to these views
>I would rather see a nice octocat icon there since the views are related to Github but I possess neither skills nor tools to craft such a vector graphic 🤷‍♂️

**Comment by simurai** [comment]
> ⚠️ A git icon has been added to these views
I would rather see a nice octocat icon there since the views are related to Github but I posses neither skills nor tools to craft such a vector graphic 🤷‍♂️

Luckily, the Octicons include a :octocat: logo. I added it with https://github.com/atom/github/pull/1927/commits/92ed3165c34f2c0b773b14ebd2526f8ab7a282b5.

screen shot 2019-01-31 at 11 29 59 am
screen shot 2019-01-31 at 11 44 13 am

**Comment by robertrossmann** [comment]
Thanks @simurai for updating the icon! 👍 

I do have some follow-up improvements in mind after I gave it some more thought during my sleep (😇), but I guess it would be best to merge this and I'll open up another PR, because those changes would be a bigger departure from current designs of these screens and you just might not like it 😄.

Thanks, looking forward to having this merged in! ❤️

**Comment by smashwilson** [comment]
> codecov seems down

Weird. I think CodeCov having trouble with this PR because it's coming from a fork?

**Pull request merged**
