### PR TITLE
Further improvements to "empty" views/modals

### PR DESCRIPTION
**Pull request by robertrossmann**
**Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* Suggestion: You can use checklists to keep track of progress for the sections on metrics, tests, documentation, and user research.

### Description of the Change

This PR builds on #1927 and includes the following changes:

- Tweaked the login flow to match the style of the reworked modals
- Replaced git/github icons with more context-specific icons where appropriate (up to discussion)
- ~Modals with buttons are now aligned to the pane's bottom instead of to the vertical centre of the pane (also up to discussion; views with no controls are still aligned to the centre)~
  > (reverted - all dialog views are now centered in the pane)

Screenshots follow. 🎨

At the very least I would like to get the login modal rework merged; the rest is really up to discussion whether or not those changes are an improvement over the current look & feel.

##### Too many changes

- new icon

too many changes

##### Unsupported directory

- new icon

unsupported directory

##### Create repository

- new icon
- ~aligned to bottom~

create repository

##### Select a Remote

- new icon
- ~aligned to bottom~

select a remote

##### Login

- added icons to both screens
- ~aligned to bottom~

login - 1
login - 2

### Alternate Designs

I guess we can just keep the original Git & Github icons everywhere. I thought that using icons which better represent the current context would improve users' understanding of what's going on without reading the text. 🤔

~As for the alignment, I think keeping everything in the middle won't hurt but for some reason I feel like the buttons _should_ be somewhere down. Maybe I'm biased from seeing too many mobile UI screens where these kinds of buttons tend to be down so as to be easily reachable with your thumb (which obviously does not matter here).~

~Screens with just a warning and no control should stay in the middle so as to catch your focus as quickly as possible. Screens with buttons are more easily perceivable due to strong colouring on those buttons.~

> All screens are now consistently aligned to the pane's centre. 🎨

### Benefits

- Improved UX by showing contextual icons instead of generic git/github icon everywhere
- For the login view, consistency with the other modals improved in #1927

### Possible Drawbacks

N/A

### Applicable Issues

N/A

### Metrics

N/A

### Tests

N/A

### Documentation

N/A

### Release Notes

Some of the less-frequently used screens (Github login, multiple remotes selection view etc.) have received visual overhaul. 🎨

### User Experience Research (Optional)

N/A

### CODE REVIEW

**Comment by 50Wliu** [comment]
> Modals with buttons are now aligned to the pane's bottom instead of to the vertical centre of the pane

I love the other changes, but this one seems a little jarring. I would expect the dialogs to be consistently centered, and it also leaves a large amount of empty space above it.

**Comment by robertrossmann** [comment]
@50Wliu Thanks for feedback! It just occurred to me that perhaps it would be better if we move the big icons consistently to the centre while preserving the buttons' placement?

Personally I like how the buttons "feel" when they are at the bottom - they seem to stick there regardless of viewport or pane size. If you align all the content to the middle the content seems to "travel" as you resize the viewport.

**Comment by simurai** [comment]
Another idea: Have 1-3 words wrapped with `<strong>` as a quick summary.

image

It's a bit like seeing a "404" on a website. After encountering this view a few times you might remember what it means and don't have to start reading from the start, you'll be like: "Ohh.. multiple remotes... ok!". The branch name would be wrapped with `<code>` instead.

**Comment by robertrossmann** [comment]
@simurai Thanks for all the suggestions. I personally like the idea of having headings on all the views for quick summary of what's going on.

To somewhat address the concern of the buttons being too far away from the tabs, I added a significant margin to all the views with buttons to push the content up a bit - the views are still pushed down but they appear a little higher now (screenshots follow).

Also I increased the icons' size to make them more prominent.

### Updated screenshots

create repo

multiple remotes

login - 1

login - 2

no remotes

Let me know your thoughts. If you still feel that the content should be centered I'll revert the placement back. Overall I like the other changes. 🎨 😇 Thanks for feedback!

**Comment by robertrossmann** [comment]
No problem @simurai, I have moved all the things to the pane's centre now. 💪

I have updated the PR's initial description (incl. screenshots) in case you'd like to review again.

I also noticed that all the other dialog views with buttons use an "imperative tone" in the headings except for the "Multiple Remotes" view, so I changed that heading to "Select a Remote" which I think better conveys the view's purpose. 🤓

**Comment by robertrossmann** [comment]
Thanks for all the feedback and review! ❤️

**Pull request merged**
