### PR TITLE
Add button for discarding hunk/selection in HunkView

### LINKED ISSUE #604: Add "Discard Hunk/Selection" button
The discard feature is awesome, but I worry many users might not discover it via the context menu. I think it warrants its own button next to the "Stage Hunk/Selection" button.

/cc @kuychaco

### PR DESCRIPTION
**Pull request by kuychaco**
Fixes #604 

/cc @simurai for styling 💭 

I'm a bit concerned that the button is so close to the "Stage/Unstage" button and therefore might accidentally get pressed. Maybe we can move it elsewhere in the hunk header? But even if it does accidentally get pressed then the user can always undo the discard.

discard-hunk

### CODE REVIEW

**Comment by simurai** [comment]
> I'm a bit concerned that the button is so close to the "Stage/Unstage" button and therefore might accidentally get pressed. Maybe we can move it elsewhere in the hunk header?

### Option A

Could be smaller, maybe just an icon:

screen shot 2017-05-25 at 5 11 56 pm


### Option B

Have the stage/unstage button on the left. Also, "Stage All". Then the good things are on the left and the evil ones on the right:

screen shot 2017-05-25 at 5 22 38 pm

--- 

✋  I tend towards Option B. It would increase the distance to travel from the lists to the stage button. Maybe ok. You can move the Git panel to the left dock, if necessary. I might do that myself, just have to override the arrow keybindings first.

**Comment by kuychaco** [comment]
> Then the good things are on the left and the evil ones on the right:

Haha I like that separation.

> It would increase the distance to travel from the lists to the stage button. Maybe ok.

How about swapping the positions so that the good things are on the right, and the evil ones are further away on the left and harder to get to.

**Comment by simurai** [comment]
> How about swapping the positions so that the good things are on the right, and the evil ones are further away on the left and harder to get to.

Hmm.. that feels a bit weird because the left side is the "main area" with the title and the blue focus. Seeing discard right above might look like it's the "main" action.

screen shot 2017-05-25 at 7 50 03 pm

We can also merge this PR as is, then do a bigger juggling things around in another one. Together with the "it's too hard to know in which list you are" #864. And maybe more.

**Comment by kuychaco** [comment]
> Hmm.. that feels a bit weird because the left side is the "main area" with the title and the blue focus. Seeing discard right above might look like it's the "main" action.

Yeah, good point. Moving the stage buttons all the way to the left feels a bit extreme to me. Don't know how much of that is my being used to having them on the right and how much of it is that it just makes more sense intuitively that they be there. It feels like the right side is more accessible and natural, there's less friction to take the action.

For now I've implemented Option A which I think is a really nice compromise. 

Thanks for your thoughts and mockups @simurai :bowing_woman:

**Pull request merged**
