### PR TITLE
Fix freezing on travis

### PR DESCRIPTION
**Pull request by BinaryMuse**
My hunch is that the test freezing we're seeing on Travis is related to Keytar. This PR disables Keytar as a valid strategy on Travis.

### CODE REVIEW

**Comment by BinaryMuse** [comment]
So much for that theory

**Comment by BinaryMuse** [comment]
Okay! I've tracked down the freeze — it seems that `fs.realpath` in this code in `workdir-cache.js` is never calling its callback:

```js
  resolvePath(unresolvedPath) {
    return new Promise((resolve, reject) => {
      fs.realpath(unresolvedPath, (err, resolved) => {
        // WE NEVER GET HERE
        if (err) {
          reject(err);
        } else {
          resolve(resolved);
        }
      });
    });
  }

```

**Comment by smashwilson** [comment]
image

Let's see what I can do with this one 😅

**Comment by smashwilson** [comment]
Here's the result of an `strace` on the stalled process:

```
Process 6700 attached with 19 threads
[pid  8744] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid  8748] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid  8746] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid  8744] <... restart_syscall resumed> ) = -1 EAGAIN (Resource temporarily unavailable)
[pid  8746] <... restart_syscall resumed> ) = -1 EAGAIN (Resource temporarily unavailable)
[pid  8744] futex(0x855c3308044, FUTEX_WAIT_BITSET_PRIVATE, 11139, {938, 550152986}, ffffffff <unfinished ...>
[pid  8746] futex(0x855c3308044, FUTEX_WAIT_BITSET_PRIVATE, 11139, {938, 562963318}, ffffffff <unfinished ...>
[pid  6703] futex(0x7fdd5b0738dc, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid  6706] futex(0x855c3356134, FUTEX_WAIT_PRIVATE, 539, NULL <unfinished ...>
[pid  6709] futex(0x855c331cdd0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  6705] futex(0x7fdd5a0718dc, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid  6716] read(38,  <unfinished ...>
[pid  8384] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid  6863] futex(0x7fdd6e4082cc, FUTEX_WAIT_PRIVATE, 12648, NULL <unfinished ...>
[pid  6862] futex(0x7fdd6e4082cc, FUTEX_WAIT_PRIVATE, 12644, NULL <unfinished ...>
[pid  8384] <... restart_syscall resumed> ) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6862] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  6861] futex(0x7fdd6e4082cc, FUTEX_WAIT_PRIVATE, 12642, NULL <unfinished ...>
[pid  8384] futex(0x855c3308044, FUTEX_WAIT_BITSET_PRIVATE, 11139, {938, 539175995}, ffffffff <unfinished ...>
[pid  6864] futex(0x7fdd6e4082cc, FUTEX_WAIT_PRIVATE, 12646, NULL <unfinished ...>
[pid  6862] futex(0x7fdd6e4082cc, FUTEX_WAIT_PRIVATE, 12648, NULL <unfinished ...>
[pid  6861] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  6707] futex(0x855c335616c, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid  6704] futex(0x7fdd5a8728dc, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid  6702] epoll_wait(26,  <unfinished ...>
[pid  6701] epoll_wait(31,  <unfinished ...>
[pid  8747] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid  6700] futex(0x7fff23ed3cb4, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid  6861] futex(0x7fdd6e4082cc, FUTEX_WAIT_PRIVATE, 12648, NULL <unfinished ...>
[pid  8747] <... restart_syscall resumed> ) = -1 EAGAIN (Resource temporarily unavailable)
[pid  8747] futex(0x855c3308044, FUTEX_WAIT_BITSET_PRIVATE, 11139, {938, 530156085}, ffffffff <unfinished ...>
[pid  6864] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  6864] futex(0x7fdd6e4082cc, FUTEX_WAIT_PRIVATE, 12648, NULL
```

Nothing in there jumps out at me. The `read()` call is this one:

https://github.com/atom/node-pathwatcher/blob/master/src/pathwatcher_linux.cc#L33

... and I'm assuming the `epoll_wait()` calls are the node and Chromium event loops. All of the `futex()` calls are low-level Linux threading primitives. It could be a deadlock?

**Comment by smashwilson** [comment]
✊ Got it. :sparkles: Long story short: it seems to be a problem with electron IPC on Linux, possibly exacerbated by the rapid creation and deletion of renderer processes. I've prevented it from happening by setting `ATOM_GITHUB_INLINE_GIT_EXEC` on the test suite on Travis and skipping the tests that directly exercise `WorkerManager`, which were also locking up periodically when the `GithubPackage` tests did not.

I'll admit that this feels just a little like "fixing" things by skipping the problem. In this case, I believe it's justified because:

* It's a specific issue that seems to occur only on Linux and only on CI. I could never reproduce it on my actual Linux machine, and I've never seen it happen in practice.
* We already have two alternatives in mind: using [spawn-server](https://github.com/nathansobo/spawn-server) if that becomes available in Atom core, or using web workers rather than a full renderer process.
* Only the WorkerManager tests themselves are actually skipped. From the perspective of the rest of the package, nothing else should care about whether or not git operations are performed in-process or not.

**Pull request merged**
