### PR TITLE
Blank states for GitHub tab

### PR DESCRIPTION
**Pull request by smashwilson**
**Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* Suggestion: You can use checklists to keep track of progress for the sections on metrics, tests, documentation, and user research.

### Description of the Change

Implement the "blank" states of the GitHub tab when:

* No repositories are open.
* The current project is not initialized as a git repository.
* The current repository has no remotes on GitHub.

I'm doing this by keying off of the active Repository's state in GitHubTabView, and launching the dialogs introduced in #2222.

Remaining work:

- [x] "Initialize and publish" fails with the message "Unable to determine the desired default branch from the repository".
- [x] "Publish on GitHub" does not push your default branch - it leaves the newly created repository empty.
- [x] Metrics
- [x] Test coverage

### Screenshots

| Situation | GitHub panel state |
| -- | -- |
| No project roots | no projects |
| Uninitialized | uninitialized |
| No remotes on GitHub | no remotes |

### Alternate Designs

See the feature request.

### Benefits

Users will no longer be presented with a blank, featureless tab if they open the GitHub tab without any repositories open (😬). The existing error view -- when the current repository has no remotes -- is improved with an action you can take, to publish it.

### Possible Drawbacks

We still don't handle Enterprise, which means that you could have a remote pointing to an Enterprise instance and we'll still tell you we don't have any GitHub remotes. Accurate, but frustrating.

### Applicable Issues

Feature request: #2111.

### Metrics

* `create-github-repository` event when a repository is created simultaneously locally and on GitHub.
* `publish-github-repository` event when an existing local repository is pushed to a newly created GitHub repository.
* `init-publish-github-repository` event when a non-git project folder is initialized and published to a newly created GitHub repository at the same time.
* `clone-repository` event when a repository is cloned with the clone dialog.

### Tests

Standard unit test coverage.

### Documentation

Flight manual documentation of the new path to the Clone dialog: https://github.com/atom/flight-manual.atom.io/pull/573

### Release Notes

* Opening the GitHub tab without an active repository with a GitHub remote offers you the ability to publish or create a new repository.

### User Experience Research (Optional)

_N/A_

### CODE REVIEW

**Comment by wadethestealth** [comment]
How did you go about drilling props? Is there a tool I can use on my PRs?

**Comment by smashwilson** [comment]
Nah. Sadly, it's all manual.

The fix there is to migrate to using hooks, which allow us to gracefully consume multiple contexts in the same component. But that effort is waiting for either (i) Enzyme to support hooks in its shallow renderer, or (ii) a gradual rework of the test suite to use mount() instead. See #1437 for some discussion and links to draft implementations of alternatives that we've explored in the past.

**Comment by wadethestealth** [comment]
Why is it your PR has codecov? Is this a draft only feature?

**Comment by smashwilson** [comment]
> Why is it your PR has codecov? Is this a draft only feature?

It's because of the way we're using Azure DevOps and its CodeCov reporter. For some reason, we only get coverage data and the coverage change comment when we have both "push" builds _and_ "pull request" builds. When you make pull requests from a fork, only the "pull request" build runs.

If I can work it out, I can try to tackle that as part of #2298.

**Pull request merged**
