### PR TITLE
Lock Relay dependencies to 1.4.1

### LINKED ISSUE #1340: Error logging into GitHub tab
### Prerequisites

:+1:

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Breaking out from https://github.com/atom/github/issues/1324#issuecomment-371650745 - when I open a project that's also a Git repository, I see this error in console:

```
Uncaught (in promise) Error: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.
    at invariant (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/fbjs/lib/invariant.js:42:21)
    at getRequest (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:42:57)
    at ReactRelayQueryRenderer._fetchForProps (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:119:27)
    at new ReactRelayQueryRenderer (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:64:46)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:295:22)
    at ReactCompositeComponentWrapper._constructComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:282:25)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:185:27)
    at Object.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:40)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:27)
    at Object.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at Object.updateChildren (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:119:57)

snip...
```

Full error:

<details>
Uncaught (in promise) Error: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.
    at invariant (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/fbjs/lib/invariant.js:42:21)
    at getRequest (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:42:57)
    at ReactRelayQueryRenderer._fetchForProps (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:119:27)
    at new ReactRelayQueryRenderer (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:64:46)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:295:22)
    at ReactCompositeComponentWrapper._constructComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:282:25)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:185:27)
    at Object.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:40)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:27)
    at Object.mountComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at Object.updateChildren (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:119:57)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:209:34)
    at ReactDOMComponent._updateChildren (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:308:37)
    at ReactDOMComponent.updateChildren (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactMultiChild.js:295:18)
    at ReactDOMComponent._updateDOMChildren (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:944:18)
    at ReactDOMComponent.updateComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:758:16)
    at ReactDOMComponent.receiveComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:720:16)
    at Object.receiveComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:558:18)
    at Object.performUpdateIfNecessary (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactReconciler.js:154:28)
    at runBatchedUpdates (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:148:27)
</details>

If I open the GitHub tab and try to login, the same error pops up every time I try to login.

### Steps to Reproduce

Assuming you need to login to the GitHub tab:

1. Open some Git repository project
2. `GitHub: Toggle GitHub tab`
3. Click `Login`
4. Generate an auth token and paste it in
5. Click `Login`

**Expected behavior:**

Login to be successful.

**Actual behavior:**

Nothing happens and an error appears in the console every time you click Login.  

I also see the error just by opening a Git repository project.

**Reproduces how often:**

100%

### Versions

```
atom -v
Atom    : 1.26.0-dev-429f2bdd0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```
apm -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-dev-429f2bdd0
python 2.7.10
git 2.14.3
```

Also repro-ed with 1.25.0-beta3.

macOS 10.12.6

Also saw this on Windows 10 with Atom 1.24.1

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

/cc @kuychaco @smashwilson

### PR DESCRIPTION
**Pull request by smashwilson**
Our custom network layer manager is currently incompatible with [Relay 1.5.0](https://github.com/facebook/relay/releases/tag/v1.5.0), I suspect because of [this signature change](https://github.com/facebook/relay/commit/c058ffc41f8cc484397c540fc6ee0ea819eedb47).

It shouldn't be a big deal to fix this the right way, but I'll lock the dependency to 1.4.1 to unblock us quickly for now.

Fixes #1340.

### CODE REVIEW

**Comment by elazrus** [comment]
I'm getting this same issue with the Github tab token login on atom 1.27.1

**Comment by PS-ChaseEdwards** [comment]
I'm currently experience the issue on version 1.32.2

**Comment by DanSman** [comment]
Yeah, same here.

**Comment by smashwilson** [comment]
Do you mean you're seeing #1340?

Is the console message identical? If so - can you comment there so we can re-open the issue and investigate? If not, can you open a new issue with the stacktrace?

**Comment by PS-ChaseEdwards** [comment]
@smashwilson I resolved the issue by simply restarting my computer. I only attempted to connect at the gui level, so I didn't see any console message. Still seems odd that it requires a restart, but now it's working flawlessly.

**Pull request merged**
