### PR TITLE
add context menu labels when items are selected

### LINKED ISSUE #940: spooky action in the context menu
The context menu won't show stage/unstage options when clicking between file names

github-context

#878 seems to have introduced this

It seems that `.github-FilePatchListView` becomes the target when clicking on the padding of a `.github-FilePatchListView-item`

I'm not sure if there is an underlying issue as to why `.github-FilePatchListView-item` is not the target or if this is just a Windows issue.

**Furthermore**, if there are unstaged files selected, I don't see why right clicking on the empty space shouldn't bring up the stage command.

# versions

Windows 10.0.16215.1000
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.13.0.windows.1
visual studio 2015
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

If files are selected, right clicking on the empty space will bring up the commands in the context menu.

github-context2

### Benefits

People won't be confused when selecting files and right clicking just underneath them. 

### Possible Drawbacks

none?

### Applicable Issues

Fixes #940
somewhat rolls back #878

### CODE REVIEW

**Comment by UziTech** [comment]
I believe this still fixes #751 like #878 was trying to

**Comment by BinaryMuse** [comment]
Thanks for the PR! I'll take a look at this as soon as I can.

**Comment by BinaryMuse** [comment]
Thanks so much for your contribution! This looks ✨

**Pull request merged**
