### PR TITLE
Align changed files count

### LINKED ISSUE #1198: Incorrect styles on github-ChangedFilesCount causes status bar tile to appear unaligned
### Description

It looks like there's a few issues with the `github-ChangedFilesCount` status bar tile.  First of all, it's outside the `span` that the other two GitHub tiles are contained in (branch select, push/pull).  Then it's an `a` instead of a `div`.  But more importantly, it has the `icon` class assigned to the tile itself rather than a sub-span, causing the tile to be ~2 pixels lower than the rest of the tiles.

github-changedfilecount-issues

/cc @simurai maybe when you're back

### PR DESCRIPTION
**Pull request by sethlu**
**Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This PR addresses a slight vertical visual offset by introducing a div wrapper around the anchor object preventing `vertical-align` inherited from `.icon`, preserving the same alignment standards.

### Alternate Designs

- Override `vertical-align: middle` inherited from `.icon` for the anchor object. However, this may result in weird text aligning.

### Benefits

It allows the background color on hover to span the whole column vertically, resolving a light margin above the clickable element.

Before change:

screenshot 2017-09-19 23 48 40

After change:

screenshot 2017-09-20 00 00 50

### Possible Drawbacks

N/A

### Applicable Issues

Fixes #1198

### CODE REVIEW

**Comment by Xapphire13** [comment]
In your screenshot it looks like it doesn't touch the right border, it should probably behave the same as the update reminder:

image

**Comment by sethlu** [comment]
@Xapphire13 The screenshot's taken from an earlier version. I'll update the PR with some changes later.

**Comment by sethlu** [comment]
New screenshots following recent changes are here:

Before:

screen shot 2017-11-06 at 6 41 31 pm

After:

screen shot 2017-11-06 at 6 42 02 pm

*And with baseline highlighted...*

Before:

before

After:

after

---

🚧  Do not merge this PR just yet, I just realized the layouts for a few other tiles have yet been investigated.

With the ones shown, a scrolling overflow is resolved.

**Comment by sethlu** [comment]
Seems that the issue's already fixed in the latest release.

**Comment by 50Wliu** [comment]
@sethlu Hmm, still seems like a problem to me:
github-sunken

I think the issue is that that status bar tile is instantiated incorrectly.

**Comment by sethlu** [comment]
Oh I just realized I’m running the dev version. 🙈

**Comment by sethlu** [comment]
Just inspected the different views and think this patch should be ready to address the existing layout problem.

**Comment by simurai** [comment]
Should we move this PR over to One light/dark?

Each theme might have different styling for the status bar items. For example, this PR would make it uneven in the `atom-light-ui` theme:

image

**Comment by sethlu** [comment]
@simurai Good question... And I'm not sure 😕 since `atom-light-ui` overwrites the default styling over these tile items.

My original intention for this PR is to address an issue with the background color for the "21 files" part when mouse on hover (there's a gap between the top border of the status bar and the tile item). In a recent change with Electron the issue is *fixed* with an `overflow: hidden` on the status bar so the overflowing background won't cause a scrolling behavior.

I can probably modify PR so the changes only address this background fill overflow for the files changed section? ... as showed in comment https://github.com/atom/github/pull/1182#issuecomment-345091954

**Comment by 50Wliu** [comment]
I just looked at this diff and I think this PR is taking the wrong approach.  As I detailed in #1198 I think the root cause is that the DOM markup for the changed files count is incorrect, not the styling.

**Comment by simurai** [comment]
> @50Wliu I think the root cause is that the DOM markup for the changed files count is incorrect

I tried this alternative approach by change the DOM markup: https://github.com/sethlu/github/pull/1. And yeah, it seems to fix the issue with the `1px` gap. 👍 

@sethlu If you like that approach, you can merge https://github.com/sethlu/github/pull/1 and it should update this one.

**Pull request closed without merging**
