### PR TITLE
Fixes PR label legibility

### PR DESCRIPTION
**Pull request by DrianHillman**
- [X]  **Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Description of the Change

This PR implements the recommended solution for issue #772. The text for PR labels in the GitHub pane will now dynamically use the most readable color (black or white) based on the set background color of the label.

### Alternate Designs

Design-wise we can play with adding more text color options to the list of arguments (i.e. off-blacks, greys, and off-whites); but this edit makes the text certainly readable which is why it was chosen. 

### Benefits

The PR labels on the GitHub pane will now be 100% readable to all users, especially those with dark themed editors! 🎉

### Possible Drawbacks

It adds 1 additional package to the project ([TinyColor](https://github.com/bgrins/TinyColor)), but it is a very low-risk implementation. This calls on only 1 of the package's methods, so the logic here may be forked if necessary (MIT License).

### Applicable Issues

None.

______

This is my first PR and I must say it is extremely exciting to contribute to Atom! I'm looking forward to contributing in the future as well!

### CODE REVIEW

**Comment by ungb** [comment]
@DrianHillman always happy to see people contributing to Atom!   One thing is that the travis build is failing.  The failure is due to:

```
/Users/travis/build/atom/github/lib/containers/pr-info-container.js
  93:60  warning  Strings must use singlequote  quotes
  93:68  warning  Strings must use singlequote  quotes

```

Can you fix these linting issues? Once the issues are fixed, I'll test the changes.

**Comment by DrianHillman** [comment]
Absolutely, good catch @ungb— I just pushed an update.

Thanks for pointing that out, I'm able to see in Travis' build where they flagged that warning. Something I'll look out for going forward! 👍🏽

Always `npm run lint`!

**Comment by ungb** [comment]
Looks good, will merge once build passes.  Rerunning.
Thanks @DrianHillman for your submission and @BinaryMuse for reviewing!

before:
image


after:
image

**Comment by ungb** [comment]
LGTM!  🎉   Thanks for submitting this PR!  Thanks @BinaryMuse with all your help!

**Pull request merged**
