### PR TITLE
add committer name to commit detail pane

### PR DESCRIPTION
**Pull request by annthurium**
### Description of the Change

This change adds the committer's full name to the commit detail pane.  Instead of email address, we show the full name.

screen shot 2019-01-15 at 1 38 23 pm

### Alternate Designs

- I considered showing the name and email address.  However, it looked kinda cluttered, and I couldn't find a good way of showing co author info in that scenario. 

image

### Benefits

- Makes it easier to understand at a glance who made the commit
- Feature has been requested by folks in the community

### Possible Drawbacks

- If folks need the email address of a committer for some reason, now it would take more effort to find it. 

### Applicable Issues

https://github.com/atom/github/issues/1875

### Metrics

N/A

### Tests

- Manually tested that committer name shows up as expected for single commits
- Commiter name shows up as expected for co authored commits
- name falls back to something reasonable (such as email address or GitHub username) if committer name is not set in git config
- all new lines covered by unit tests

### Documentation

N/A

### Release Notes

TBD

### User Experience Research (Optional)

N/A

### CODE REVIEW

**Comment by annthurium** [comment]
hey @simurai -- this isn't urgent, but if you feel like making this look better, that'd be cool.

Right now it's like: 
screen shot 2019-01-11 at 4 46 20 pm

**Comment by annthurium** [comment]
Note for future Tilde or whomever ends up picking this up...

I tried testing the case where the commiter name does not exist by unsetting my email, username, and github handle in my git config.  Git won't let you commit without one of those things set.

If I unset my github user alias, somehow `name` is falling back to `annthurium`.  So weird!  I don't think it's being pulled from my email address either, because I tried modifying that. Needs further investigation.

**Comment by smashwilson** [comment]
From now on, all of my commit messages will be "hunks hunks hunks"

**Comment by simurai** [comment]
How about replacing the current email with the author name and not have both?

image

And only use the email as a fallback if name or username doesn't exist?

Then the case of multiple authors should also be covered. E.g. `[name] and 3 others committed...`.

**Comment by annthurium** [comment]
@simurai I like that!  I'll move this in that direction.

**Review by simurai — APPROVED** [review]

**Pull request merged**
